### ISSUE TITLE
Adding messages to conversations you're not a part of

### ISSUE THREAD

**Issue by ewasion** [MangaDex/Bugs#10]
### Repro Steps
1. Send a POST request to https://mangadex.com/ajax/actions.ajax.php with the following parameters
```
function=msg_reply
id=107
```

### Expected occurrence
You get an error, because you're not part of this DM

### Actual occurrence
Your message is added to the conversation

### Impact on user
Other users' DMs can be spammed with unrelated messages

### Repro success-rate
100%

### Browser(s) used/tested
Firefox Nightly 59.0a1

**Comment by misteranonimous** [comment]
Fixed!
