### ISSUE TITLE
Long comments extend tables

### ISSUE THREAD

**Issue by ewasion** [MangaDex/Bugs#11]
### Repro Steps
1. Visit a manga page
2. Post a very long comment (with no whitespace)

### Expected occurrence
The comment is contained within the viewport

### Actual occurrence
The comment extends the table, leaving the viewport

### Impact on user
Has to deal with an annoying horizontal scrollbar and has to scroll all the way to report or delete comments

### Repro success-rate
100%

### Browser(s) used/tested
Firefox Nightly 59.0a1

**Comment by ewasion** [comment]
### Possible fix
Add `word-break: break-all;` to `#comments tr`

**Comment by misteranonimous** [comment]
Fixed
