### ISSUE TITLE
Genre XSS/Adding arbitrary genres

### ISSUE THREAD

**Issue by ewasion** [MangaDex/Bugs#12]
### Repro Steps
1. Visit a manga page
2. Press edit
3. Edit one of the `manga_genres[]` fields' value
4. Press save

### Expected occurrence
An error message shows up, telling the user this tag isn't allowed

### Actual occurrence
Not only is the arbitrary tag added, but it also isn't properly escaped

### Impact on user
Can be forced to send any request, can be done within a hidden iframe or just browsing the website

### Repro success-rate
100%

### Browser(s) used/tested
Firefox Nightly 59.0a1

**Comment by misteranonimous** [comment]
Fixed
