### ISSUE TITLE
[Bug] Handle trailing slashes in URLs properly instead of redirecting to /

### ISSUE THREAD

**Issue by Travanoid** [MangaDex/Bugs#15]
### Reproduction steps

1. Navigate to any manga or chapter page on the site
2. In the URL bar, add a / to the end of the URL
3. Hit Enter

### Expected occurrence
The trailing slash is ignored and the page is displayed as expected.

### Actual occurrence
The user is redirected to the home page
### Impact on users
The user ends up on the home page and is unsure why
### Tested on
Chrome Version 64.0.3282.119 (Official Build) (64-bit)

**Comment by misteranonimous** [comment]
Fixed.
