### ISSUE TITLE
[Bug] H-toggle and manga use different tags for the same thing

### ISSUE THREAD

**Issue by Travanoid** [MangaDex/Bugs#19]
### Reproduction steps

1. Find a manga on that is tagged with [H]
2. Expand the H-toggle dropdown at the top of the page

### Expected occurrence
The same tagging is used for the drop-down and individual manga labels

### Actual occurrence
The drop-down displays an [R18+] tag while individual manga are tagged with [H]

### Impact on users
The user may not realize that [R18+] and [H] are the same thing

### Possible resolution
Change one of the locations so that the tagging is consistent across the site

### Screenshot
![image](https://user-images.githubusercontent.com/28797307/35716896-90c63e98-0790-11e8-998b-8bd8568c7071.png)

**Comment by misteranonimous** [comment]
Fixed
