### ISSUE TITLE
Broken stylesheet links after password reset

### ISSUE THREAD

**Issue by ewasion** [MangaDex/Bugs#2]
### Repro Steps
1. Log in
2. Reset your password (on a separate browser/incognito mode/ask someone to do it for you)

### Expected occurrence
The user is logged out

### Actual occurrence
The user is logged out, but because all session variables are deleted, stylesheets stop loading.  
`/bootstrap/css/bootstrap..css?v=1` instead of `/bootstrap/css/bootstrap.1.css?v=1`

### Impact on user
This is confusing, and only goes away once cookies are cleared. Most users wouldn't do that and stop using the website.

### Repro success-rate
100%

### Browser(s) used/tested
Firefox Nightly 59.0a1

**Comment by ewasion** [comment]
### Possible fix
Make the theme ID default to something when it's blank

**Comment by misteranonimous** [comment]
Fixed.
