### ISSUE TITLE
[Bug] Searches containing the ' character return no results

### ISSUE THREAD

**Issue by LucasPratas** [MangaDex/Bugs#25]
### Reproduction steps
1. Find an existing manga entry containing the `'` character in the title
2. Insert the title in the search bar and submit

### Expected occurrence
The manga entry is found by the search

### Actual occurrence
The manga entry is not found by the search

### Impact on users
Users unaware of the issue will believe the manga has not yet been added to the website, becoming disappointed, and possibly even going as far as to add an entry for that (already-existing) manga, resulting in duplicate entries. Users aware of the issue are forced to either search for their manga while circumventing the use of `'`, resulting in slightly degraded searching experience, or searching for their manga by navigating through several pages of the titles page, resulting in severely degraded searching experience.

### Screenshots
![2018-02-02_04-50-41_vivaldi](https://user-images.githubusercontent.com/28331593/35720394-b7e97b5e-07d4-11e8-918c-bd29af284a24.png)

![2018-02-02_04-50-57_vivaldi](https://user-images.githubusercontent.com/28331593/35720400-bad6e02c-07d4-11e8-90a1-4cc762cc17dd.png)

**Comment by misteranonimous** [comment]
Fixed
