### ISSUE TITLE
[Bug] Multiple groups working on the same chapter breaks the reader.

### ISSUE THREAD

**Issue by BraveDude8** [MangaDex/Bugs#27]
https://mangadex.com/chapter/6812/1 Group1, V2C8, displays as V1C1 and sends you to V1C2. This was uploaded first.

https://mangadex.com/chapter/4531/1 Group2, V2C8, displays as V2C8 and sends you to V2C9. This was uploaded second.

As far as I can tell, if there's more than one version of a chapter the reader navigation breaks for all but the most recently uploaded.

**Comment by BraveDude8** [comment]
I think the issue got flipped at some point, now the opposite is occurring and the most recently uploaded chapter is the one breaking instead.

**Comment by misteranonimous** [comment]
Fixed
