### ISSUE TITLE
Chapter edition is unrestricted

### ISSUE THREAD

**Issue by ewasion** [MangaDex/Bugs#28]
### Repro Steps
1. Send a POST request to `https://mangadex.com/ajax/actions.ajax.php?function=chapter_edit&id=XXX` (replace XXX with the chapter ID) and parameters `manga_id` (int-like string), `chapter_name` (string), `volume_number` (int-like string), `chapter_number` (int-like string), `group_id` (int-like string), `lang_id` (int-like string), `old_file` (unsure), `file` (image file(?)/zip).

### Expected occurrence
An error is displayed if the user shouldn't edit this chapter

### Actual occurrence
The chapter is edited, regardless of the user's permissions

### Impact on user
Griefing is made possible

### Repro success-rate
100%

### Browser(s) used/tested
Firefox Nightly 59.0a1

**Comment by misteranonimous** [comment]
Fixed
