### ISSUE TITLE
Passwords are instantly reset, without confirmation

### ISSUE THREAD

**Issue by ewasion** [MangaDex/Bugs#3]
### Repro Steps
1. Visit the [login page](https://mangadex.com/login) and press "Reset Password"
2. Submit your account's email

### Expected occurrence
A confirmation email is sent, clicking a link in the email lets the user reset their password

### Actual occurrence
The user's password is instantly reset, with no way to confirm the account owner issued the password reset

### Impact on user
Anyone knowing the user's email can force them to log out and to check their inbox to find the new password (which might take a while, because their old password is now invalid and #2)

### Repro success-rate
100%

### Browser(s) used/tested
Firefox Nightly 59.0a1

**Comment by misteranonimous** [comment]
Fixed.
