### ISSUE TITLE
Session tokens are still valid after logging out

### ISSUE THREAD

**Issue by ewasion** [MangaDex/Bugs#30]
### Repro Steps
1. Log in
2. Copy the "mangadex" cookie
3. Log out
4. Set the "mangadex" cookie
5. Reload the page

### Expected occurrence
You're still a guest because the token is now invalid

### Actual occurrence
You're logged back in

### Impact on user
If session cookies get stolen, they can still be used after the user logs out.

### Repro success-rate
100%

### Browser(s) used/tested
Firefox Nightly 59.0a1

**Comment by misteranonimous** [comment]
Fixed, a new session token gets generated when you log out.
