### ISSUE TITLE
[Bug] Language flags in the reader's groups drop-down are incorrect

### ISSUE THREAD

**Issue by LucasPratas** [MangaDex/Bugs#31]
### Reproduction steps
1. Find a manga entry which has a chapter available in multiple languages
2. Open the chapter in one of the languages
3. Click on the groups drop-down

### Expected occurrence
All the groups which have a version of this chapter show up in the drop-down, with their respective language flag next to them.

### Actual occurrence
All the groups which have a version of this chapter show up in the drop-down, with the language flag for the currently selected group next to all of them.

### Impact on users
Users can be confused, thinking that there is another version available in their language, but being presented another language when selecting it.

### Screenshots

![2018-02-05_06-14-24_vivaldi](https://user-images.githubusercontent.com/28331593/35794201-ef3f5b1e-0a3b-11e8-9cd0-f1819bf3288d.png)
![2018-02-05_06-14-43_vivaldi](https://user-images.githubusercontent.com/28331593/35794210-f414b972-0a3b-11e8-920b-dbfb5259e23c.png)
![2018-02-05_06-17-53_vivaldi](https://user-images.githubusercontent.com/28331593/35794289-510abd02-0a3c-11e8-9eca-c18979dd2c0d.png)

**Comment by misteranonimous** [comment]
FIxed
