### ISSUE TITLE
Search XSS

### ISSUE THREAD

**Issue by ewasion** [MangaDex/Bugs#9]
### Repro Steps
1. Visit [this page](https://mangadex.com/?page=search&title=%22%20type%3D%22text%22%3E%3Cscript%3Ealert(1)%3C%2Fscript%3E%3Cimg%20src%3D%22https://mangadex.com/images/user_logos/default2.png&author=&artist=&genres=)

### Expected occurrence
Text displays within the search input

### Actual occurrence
The search query is echo'd directly inside the document, causing an alert and an image to display

### Impact on user
Can be forced to send any request, can be done within a hidden iframe

### Repro success-rate
100%

### Browser(s) used/tested
Firefox Nightly 59.0a1

**Comment by misteranonimous** [comment]
Forgot the damn ENT_QUOTES!
